
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.10.1
 * Query Engine version: 9b628578b3b7cae625e8c927178f15a170e74a9c
 */
Prisma.prismaVersion = {
  client: "6.10.1",
  engine: "9b628578b3b7cae625e8c927178f15a170e74a9c"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password_hash: 'password_hash',
  first_name: 'first_name',
  last_name: 'last_name',
  phone: 'phone',
  is_admin: 'is_admin',
  email_notifications: 'email_notifications',
  marketing_preferences: 'marketing_preferences',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.TheatreScalarFieldEnum = {
  id: 'id',
  name: 'name',
  city: 'city',
  country: 'country',
  description: 'description',
  history: 'history',
  website: 'website',
  founded_year: 'founded_year',
  photos: 'photos',
  content_language: 'content_language',
  translation_group: 'translation_group',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.TheatreImageScalarFieldEnum = {
  id: 'id',
  theatre_id: 'theatre_id',
  image_url: 'image_url',
  caption: 'caption',
  is_primary: 'is_primary',
  created_at: 'created_at'
};

exports.Prisma.TheatreTagScalarFieldEnum = {
  id: 'id',
  theatre_id: 'theatre_id',
  tag_name: 'tag_name',
  created_at: 'created_at'
};

exports.Prisma.VenueScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  address: 'address',
  city: 'city',
  capacity: 'capacity',
  image_url: 'image_url',
  created_at: 'created_at'
};

exports.Prisma.VenueSectionScalarFieldEnum = {
  id: 'id',
  venue_id: 'venue_id',
  section_name: 'section_name',
  section_type: 'section_type',
  created_at: 'created_at'
};

exports.Prisma.SeatScalarFieldEnum = {
  id: 'id',
  venue_section_id: 'venue_section_id',
  row_number: 'row_number',
  seat_number: 'seat_number',
  is_available: 'is_available',
  is_accessible: 'is_accessible',
  created_at: 'created_at'
};

exports.Prisma.EventScalarFieldEnum = {
  id: 'id',
  title: 'title',
  theatre_id: 'theatre_id',
  venue_id: 'venue_id',
  event_type: 'event_type',
  event_date: 'event_date',
  event_time: 'event_time',
  description: 'description',
  price: 'price',
  image_url: 'image_url',
  poster_url: 'poster_url',
  language: 'language',
  content_language: 'content_language',
  translation_group: 'translation_group',
  performance_language: 'performance_language',
  subtitle_language: 'subtitle_language',
  genre: 'genre',
  company: 'company',
  director: 'director',
  cast: 'cast',
  subtitles: 'subtitles',
  duration: 'duration',
  is_featured: 'is_featured',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.BookingScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  event_id: 'event_id',
  booking_reference: 'booking_reference',
  total_amount: 'total_amount',
  booking_status: 'booking_status',
  attendee_names: 'attendee_names',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.BookedSeatScalarFieldEnum = {
  id: 'id',
  booking_id: 'booking_id',
  seat_id: 'seat_id',
  attendee_name: 'attendee_name',
  qr_code_data: 'qr_code_data',
  scanned_at: 'scanned_at',
  created_at: 'created_at'
};

exports.Prisma.NewsArticleScalarFieldEnum = {
  id: 'id',
  title: 'title',
  excerpt: 'excerpt',
  content: 'content',
  category: 'category',
  image_url: 'image_url',
  author: 'author',
  content_language: 'content_language',
  translation_group: 'translation_group',
  published_at: 'published_at',
  is_published: 'is_published',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.AboutPageScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  mission: 'mission',
  vision: 'vision',
  history: 'history',
  image_url: 'image_url',
  content_language: 'content_language',
  translation_group: 'translation_group',
  is_published: 'is_published',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.ContactPageScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  address: 'address',
  phone: 'phone',
  email: 'email',
  office_hours: 'office_hours',
  map_embed: 'map_embed',
  content_language: 'content_language',
  translation_group: 'translation_group',
  is_published: 'is_published',
  created_at: 'created_at',
  updated_at: 'updated_at'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.SectionType = exports.$Enums.SectionType = {
  regular: 'regular',
  balcony: 'balcony'
};

exports.EventType = exports.$Enums.EventType = {
  performance: 'performance',
  workshop: 'workshop',
  discussion: 'discussion'
};

exports.BookingStatus = exports.$Enums.BookingStatus = {
  pending: 'pending',
  confirmed: 'confirmed',
  cancelled: 'cancelled'
};

exports.Prisma.ModelName = {
  User: 'User',
  Theatre: 'Theatre',
  TheatreImage: 'TheatreImage',
  TheatreTag: 'TheatreTag',
  Venue: 'Venue',
  VenueSection: 'VenueSection',
  Seat: 'Seat',
  Event: 'Event',
  Booking: 'Booking',
  BookedSeat: 'BookedSeat',
  NewsArticle: 'NewsArticle',
  AboutPage: 'AboutPage',
  ContactPage: 'ContactPage'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
