const performances = [
  {
    id: "1",
    title: "No Man's Land",
    company: ["Macedonian National Theatre"],
    director: "Aleksandar Morfov",
    cast: [
      "Saško Kocev",
      "Toni Mihajlovski/Nikola Aceski",
      "Aleksandar Mihajlovski",
      "Gorast Cvetkovski",
      "Aleksandar Mikić",
      "Tome Stankovski",
      "Aleksandar Gjorgieski",
      "Borče Načev",
      "Oliver Mitkovski",
      "Kamka Tocinovski/Sofia Nasevska-Trifunovska",
      "Nenad Anđelković",
      "Nikola Stefanov/Tome Stankovski/Aleksandar Ivanovski",
      "Stefan Spasov",
      "Grigor Jovanovski/Alexander Ivanovski",
      "Kristina Gieva",
      "Filip Milenkoski",
      "Marija Kondovska",
      "Tome Stankovski",
      "Aleksandar Ivanovski",
    ],
    date: "20-09-2025",
    time: "19:00",
    venue: "Main Stage",
    imageUrl: "/nizhija_zemja1.jpg",
    posterUrl: "/nichija_zemja.jpg",
    genre: "Drama",
    language: "Macedonian",
    duration: "120 minutes",
    synopsis:
      "The script No Man's Land by Danis Tanović is about the war that took place in the 1990s within the borders of the former Yugoslavia. The reason is similar to that of all wars that have occurred - the aggressive persistence and imposition of a kind of cultural identity (including religious affiliation) that is mixed with territorial, political and economic claims. What is interesting in this case is that the warring parties - the Bosniaks and the Bosnian Serbs - are very close in every sense. Hence the impression that the irreconcilable differences between them are inessential, and the conflict is unsustainable. They are at war, even unable to determine exactly why and how it all began - they ask themselves, but do not find an answer. But they continue to kill each other... If this text still manages to build on something a little different from the already widely developed military theme, it consists in the emergence of the terrible and endless inertia of destruction.",
    subtitles: "English, Bulgarian",
  },
  {
    id: "2",
    title: "Don Juan",
    company: ["National Theatre in Niš"],
    director: "Vasil Vasilev",
    cast: [
      "Dejan Lilić",
      "Dragiša Veljković",
      "Maja Vukojević Cvetković",
      "Andrija Mitić",
      "Uroš Milojević",
      "Katarina Mitić Pavlović",
      "Katarina Arsić",
      "Danilo Petrović",
      "Marjan Todorović",
      "Miloš Mitrović",
    ],
    date: "18-09-2025",
    time: "19:00",
    venue: "Main Stage",
    imageUrl: "/don_zhuan1.jpg",
    posterUrl: "/don_zhuan.jpg",
    genre: "Drama",
    language: "Serbian",
    duration: "120 minutes",
    synopsis:
      "A person's life journey and the marks they leave on others, their constant pursuit of self-improvement, give them the opportunity to rise freely and destroy all the delusions that time brings. This is my Don Juan – the one who can transcend himself and no longer be Don Juan.",
    subtitles: "English, Bulgarian",
  },
  {
    id: "3",
    title: "Oh My God",
    company: ['"Ivan Vazov" National Theatre'],
    director: "Stoyan Radev",
    cast: [
      "Hristo Mutafchiev"
    ],
    date: "21-09-2025",
    time: "16:00",
    venue: "Chamber Stage",
    imageUrl: "/1bozhe_moj.jpg",
    posterUrl: "/bozhe_moj.jpg",
    genre: "Monodrama",
    language: "Bulgarian",
    duration: "90 minutes",
    synopsis:
      "A lonely man at a bar table turns to the other visitors. It turns out that the bar belongs to Judas and the man is Christ. Or so He claims. Why? What does He want to accomplish if it is really Him? The play \"Oh My God\" is a call for humanity and love in times when God's word is misused and instead of being a source of life, it is used to justify destruction. The team of the show invites you to a warm, sincere conversation about the deepest topic that seeks answers in the heart and mind of every person. A conversation with a smile and a tear, with irony and compassion.",
    subtitles: "English, Macedonian",
  },
  {
    id: "4",
    title: "Aivar or Lutenitsa",
    company: ['OSAIK "39 Monkeys"', 'Intimate Theatre Bitola'],
    director: "Gergana Dimitrova",
    cast: [
      "Denitsa Darinova",
      "Sofia Ristevska"
    ],
    date: "20-09-2025",
    time: "16:00",
    venue: "Chamber Stage",
    imageUrl: "/a_ili_lj1.jpg",
    posterUrl: "/a_ili_lj.png",
    genre: "Comedy",
    language: "Bulgarian and Macedonian",
    duration: "",
    synopsis:
      "Denitsa is Bulgarian and Sofia is Macedonian. Two women competing on stage. Two women measure the similarities and differences between the two peoples and create their map of the Balkans with a lot of humor, music, self-irony and personal stories. The political disputes between two countries seen through the eyes of two women and their thoughts, dreams, problems, experiences and fantasies. Do common things divide us more than they unite us? Is the past really important for countries, and for women - the future?",
    subtitles: "English",
  },
  {
    id: "5",
    title: "Artists in waiting",
    company: ['Drama Theatre "Krum Kyulyavkov"'],
    director: "Presiyan Kuzov",
    cast: [
      "Yordan Danchev", 
      "Tsvetelina Nikolova", 
      "Bilyana Lachezarova", 
      "Adriana Petrova", 
      "Lazar Panev", 
      "Kostadin Zhekov", 
      "Ivana Ivanova", 
      "Yavor Borisov (voice)"
    ],
    date: "19-09-2025",
    time: "19:30",
    venue: "Main Stage",
    imageUrl: "/a_in_wait1.jpg",
    posterUrl: "/artists_in_waiting.jpg",
    genre: "Comedy",
    language: "Bulgarian",
    duration: "",
    synopsis:
      '"Waiting Artists" is a comedy that caricatures the lives of people in the world of theater. The action takes place in the summer of 1953. George and Charlotte Hay, failed Broadway stars, try to regain their former glory by playing in Buffalo, New York. The multi-layered characters of the characters and the constant dramatic twists skillfully written by the author Ken Ludwig guarantee laughter in the hall.',
    subtitles: "English, Macedonian",
  },
  {
    id: "6",
    title: "In the Dark",
    company: ['"Ivan Vazov" National Theatre'],
    director: "Albena Stavreva",
    cast: ["Albena Stavreva"],
    date: "21-09-2025",
    time: "19:00",
    venue: "Main Stage",
    imageUrl: "/nevedenie1.jpg",
    posterUrl: "/nevedenie.jpg",
    genre: "Monodrama",
    language: "Bulgarian",
    duration: "90 minutes",
    synopsis:
      '"You think I\'m tellin\' you \'bout things I\'ve seen, but no. All of these are just miracles, this is all just ignorance and if we could see \'em, they\'d transform into visions." With a jar of jam and an old suitcase Gichka the Cuckoo, the adopted daughter of the village priest, is alone in the belfry of the church. Her stories are unbelievably funny and offer a passage to a small village and its absurd, but lost world. Her stories are also sad as the trusting nature of a child is incapable of seeing through the veil of evil, even if it is staring it in the face. This is a tale of loneliness for those who are different, of frantic living on the margins of sanity and unconditional love. A life filled with memories and wonder. All of them were kept in a tiny tinder box.',
    subtitles: "English, Macedonian",
  },
];

module.exports = { performances };